#!/bin/bash
git config --global user.email "aghiles.data@gmail.com"
git add .
git submodule add https://github.com/Aghiles8/These_.git Latex/src
git submodule add https://github.com/Aghiles8/R.git R/src
git commit -m "commit"
git remote add origin https://github.com/BRICOMATA/Bricomata_.git
git rm -r --cached /home/aghiles/Aghiles/Ubuntu/conf/.thunderbird/4oyoecim.default/ImapMail/.lip6.fr
git push -u -f origin master
firefox https://github.com/BRICOMATA/Bricomata_.git
