#!/bin/sh

sh /home/aghiles/Aghiles/Latex/src/these/compile &
sh /home/aghiles/Aghiles/Latex/src/these_slide/compile &

#sh /home/aghiles/Aghiles/Latex/src/paper/compile &
#sh /home/aghiles/Aghiles/Latex/src/paper_slide/compile &

#sh /home/aghiles/Aghiles/Latex/src/survey/compile &

#gedit --new-window /home/aghiles/Aghiles/Latex/src/survey/survey.tex &

gedit --new-window /home/aghiles/Aghiles/Latex/src/these/these.tex &
gedit --new-window /home/aghiles/Aghiles/Latex/src/these_slide/these_slide.tex &

#gedit --new-window /home/aghiles/Aghiles/Latex/src/paper/paper.tex &
#gedit --new-window /home/aghiles/Aghiles/Latex/src/paper_slide/paper_slide.tex &

sh /home/aghiles/Aghiles/Latex/bin/Zotero/zotero &

rstudio /home/aghiles/Aghiles/R/src/PI_enron/src/enron_mail.r &
#gnome-terminal --working-directory=/home/aghiles/Aghiles/Latex/res/storage &

#thunderbird &
#gnome-calendar &



