#!/bin/sh

/home/aghiles/Aghiles/Latex/src/these/compile &
/home/aghiles/Aghiles/Latex/src/these_slide/compile &
/home/aghiles/Aghiles/Latex/src/paper0/compile &
/home/aghiles/Aghiles/Latex/src/paper0_slide/compile &
/home/aghiles/Aghiles/Latex/src/survey0/compile &
#sh /home/aghiles/Aghiles/Latex/src/survey0_slide/compile &

gedit --new-window /home/aghiles/Aghiles/Latex/src/these/these.tex &
gedit --new-window /home/aghiles/Aghiles/Latex/src/these_slide/these_slide.tex &
gedit --new-window /home/aghiles/Aghiles/Latex/src/paper0/paper0.tex &
gedit --new-window /home/aghiles/Aghiles/Latex/src/paper0_slide/paper0_slide.tex &
gedit --new-window /home/aghiles/Aghiles/Latex/src/survey0/survey0.tex &
#gedit --new-window /home/aghiles/Aghiles/Latex/src/survey0_slide/survey0_slide.tex &

/home/aghiles/Aghiles/Latex/bin/Zotero/zotero &
rstudio /home/aghiles/Aghiles/R/src/PI_enron/src/enron_mail.r &

#gnome-terminal --working-directory=/home/aghiles/Aghiles/Latex/res/storage &
#thunderbird &
#gnome-calendar &



