#!/bin/sh
# [Gedit Tool]
# Output=replace-selection
# Save-files=nothing
# Applicability=all
# Name=Auto Indent 2
# Input=selection-document
# Shortcut=<Primary>y


sed -z -r '
	s/\.[ \t]+\n+/vgyhn/g
	s/\n[\t ]*/ /g
	s/\. +([A-Z\\])/\.\n\1/g
	s/([,:;]) ([^0-9])/\1\n\t\2/g
	s/vgyhn/\.\n/g
	s/\- //g'
#	s/([\-\_])/\\\1/g'
#sed -r 's/\. +(\\s)/\.\n\n\1/g'
