#!/bin/sh
# [Gedit Tool]
# Name=Textbf
# Input=selection
# Output=replace-selection
# Applicability=always
# Save-files=nothing
# Shortcut=<Primary><Super>b
# Languages=


sed -z -r '
	s/(.*)/\\textbf{\1}/g'

