#!/bin/bash
#~/.local/share/gedit/plugins
cp -av /usr/lib/gedit gedit
mkdir .config
cp -av ~/.config/gedit .config
mkdir .mozilla
cp -av ~/.mozilla/firefox/*.default/browser-extension-data .mozilla
cp -av ~/.mozilla/firefox/*.default/extensions .mozilla
cp -av ~/.mozilla/firefox/*.default/extensions.ini .mozilla
cp -av ~/.mozilla/firefox/*.default/extensions.json .mozilla
cp -av ~/.mozilla/firefox/*.default/extension-settings.json .mozilla
cp -av ~/.mozilla/firefox/*.default/places.sqlite .mozilla
cp -av ~/.zotero .
cp -av ~/.thunderbird .
cp -av ~/.Renviron .
cp -av ~/.bash_history .
