#!/bin/bash
#~/.local/share/gedit/plugins
cp -av gedit /usr/lib
#cp -av .config/gedit ~/.config
#cp -av .mozilla/* ~/.mozilla/firefox/*.default
#cp -av .zotero ~
#cp -av .thunderbird ~
#cp -av .Renviron ~
#cp -av .bash_history ~
